kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    tier: backend
    app: nginx
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 32380
  selector:
    tier: backend
    app: nginx
  type: LoadBalancer